"use client";

import { FormEvent, useEffect, useState } from "react";
import ClienteForm from "@/components/ClienteForm";
import { clienteInicial, excluirCliente, listarClientes, salvarCliente, type Cliente, type ClienteForm as Form, type Pessoa } from "@/lib/clientes";

export default function Clientes() {
  const [open, setOpen] = useState(false); const [pessoa, setPessoa] = useState<Pessoa | null>(null); const [form, setForm] = useState<Form>(clienteInicial); const [clientes, setClientes] = useState<Cliente[]>([]); const [editando, setEditando] = useState<Cliente | null>(null); const [busca, setBusca] = useState(""); const [loadingCep, setLoadingCep] = useState(false); const [error, setError] = useState<string | null>(null);
  const set = (key: string, value: string) => setForm(old => ({ ...old, [key]: value }));
  useEffect(() => { setClientes(listarClientes()); }, []);
  const visiveis = clientes.filter(cliente => [cliente.nome, cliente.documento, cliente.telefone, cliente.municipio].join(" ").toLowerCase().includes(busca.toLowerCase()));
  function iniciar() { setOpen(true); setPessoa(null); setForm(clienteInicial); setEditando(null); setError(null); }
  async function buscarCep() { const cep = form.cep.replace(/\D/g, ""); if (cep.length !== 8) { setError("Digite os 8 números do CEP."); return; } setLoadingCep(true); setError(null); try { const response = await fetch(`/api/cep?cep=${cep}`); const json = await response.json(); if (!json.ok) { setError(json.error ?? "CEP não encontrado."); return; } setForm(old => ({ ...old, cep: json.data.cep || old.cep, endereco: json.data.endereco || "", bairro: json.data.bairro || "", municipio: json.data.municipio || "", uf: json.data.uf || "", codigoMunicipio: json.data.codigoMunicipio || "", complemento: json.data.complementoCep || old.complemento })); } catch { setError("Falha de rede ao buscar o CEP."); } finally { setLoadingCep(false); } }
  function editar(cliente: Cliente) { const { id, pessoa: tipo, ...dados } = cliente; setForm({ ...clienteInicial, ...dados }); setPessoa(tipo); setEditando(cliente); setError(null); setOpen(true); }
  function excluir(cliente: Cliente) { if (!window.confirm(`Excluir o cliente ${cliente.nome}?`)) return; setClientes(excluirCliente(cliente.id)); }
  function salvar(event: FormEvent) { event.preventDefault(); if (!pessoa || !form.nome || !form.documento || !form.telefone || !form.cep || !form.endereco || !form.numero) { setError("Preencha os campos obrigatórios, inclusive endereço e número."); return; } const registro: Cliente = { id: editando?.id ?? crypto.randomUUID(), pessoa, ...form }; setClientes(salvarCliente(registro)); setOpen(false); setPessoa(null); setEditando(null); setForm(clienteInicial); }
  return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-brand-600">CRM</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Clientes</h1><p className="mt-1 text-sm text-slate-500">Cadastre compradores, vendedores e contatos da loja.</p></div><button onClick={iniciar} className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">+ Adicionar novo cliente</button></header>
    {!open && <ClientesLista clientes={visiveis} busca={busca} setBusca={setBusca} onAdicionar={iniciar} onEditar={editar} onExcluir={excluir}/>}
    {open && !pessoa && <TipoPessoa onEscolher={setPessoa} onCancelar={() => setOpen(false)}/>}
    {open && pessoa && <form onSubmit={salvar} className="mt-7 space-y-6"><div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4"><div><p className="text-xs font-semibold uppercase text-slate-400">Novo cliente</p><p className="text-sm font-semibold text-slate-800">{pessoa === "fisica" ? "Pessoa física" : "Pessoa jurídica"}</p></div><button type="button" onClick={() => setPessoa(null)} className="text-sm font-semibold text-brand-600">Alterar tipo</button></div><ClienteForm pessoa={pessoa} form={form} set={set} error={error} loadingCep={loadingCep} onBuscarCep={buscarCep}/><div className="sticky bottom-3 flex justify-end gap-3 rounded-xl border border-slate-200 bg-white/95 p-3 shadow-lg"><button type="button" onClick={() => setOpen(false)} className="px-4 py-2.5 text-sm font-semibold text-slate-600">Cancelar</button><button className="rounded-lg bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white">Salvar cliente</button></div></form>}</div>;
}

function ClientesLista({ clientes, busca, setBusca, onAdicionar, onEditar, onExcluir }: { clientes: Cliente[]; busca: string; setBusca: (value: string) => void; onAdicionar: () => void; onEditar: (cliente: Cliente) => void; onExcluir: (cliente: Cliente) => void }) {
  const [menu, setMenu] = useState<string | null>(null);
  if (!clientes.length) return <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-semibold text-slate-900">Sua base de clientes começa aqui</h2><p className="mt-2 text-sm text-slate-500">Escolha pessoa física ou jurídica antes de preencher o cadastro. O CEP completa o endereço.</p><button onClick={onAdicionar} className="mt-5 text-sm font-semibold text-brand-600">Adicionar primeiro cliente →</button></div>;
  return <section className="mt-7 overflow-visible rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-slate-900">Clientes cadastrados</h2><p className="mt-1 text-xs text-slate-500">{clientes.length} cliente{clientes.length > 1 ? "s" : ""} encontrado{clientes.length > 1 ? "s" : ""}.</p></div><input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Buscar nome, CPF/CNPJ ou telefone" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand-500 sm:w-72"/></div><div className="divide-y divide-slate-100">{clientes.map(cliente => <div key={cliente.id} className="relative flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-brand-50 text-sm font-bold text-brand-700">{cliente.pessoa === "fisica" ? "PF" : "PJ"}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{cliente.nome}</p><p className="mt-0.5 text-xs text-slate-500">{cliente.documento} · {cliente.telefone}</p></div><div className="text-sm text-slate-600">{[cliente.municipio, cliente.uf].filter(Boolean).join(" - ") || "Endereço não informado"}</div><div className="relative"><button type="button" onClick={() => setMenu(menu === cliente.id ? null : cliente.id)} className="rounded-lg px-3 py-2 text-lg leading-none text-slate-500 hover:bg-slate-100 hover:text-slate-900" aria-label={`Ações de ${cliente.nome}`}>•••</button>{menu === cliente.id && <div className="absolute right-0 z-20 mt-1 w-32 overflow-hidden rounded-lg border border-slate-200 bg-white py-1 text-sm shadow-lg"><button type="button" onClick={() => { setMenu(null); onEditar(cliente); }} className="w-full px-3 py-2 text-left text-slate-700 hover:bg-slate-50">Editar</button><button type="button" onClick={() => { setMenu(null); onExcluir(cliente); }} className="w-full px-3 py-2 text-left text-red-600 hover:bg-red-50">Excluir</button></div>}</div></div>)}</div></section>;
}
function TipoPessoa({ onEscolher, onCancelar }: { onEscolher: (pessoa: Pessoa) => void; onCancelar: () => void }) { return <section className="mx-auto mt-8 max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Passo 1 de 2</p><h2 className="mt-2 text-xl font-bold text-slate-900">Qual é o tipo deste cliente?</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><button onClick={() => onEscolher("fisica")} className="rounded-xl border-2 border-slate-200 p-5 text-left hover:border-brand-500"><p className="font-semibold">Pessoa física</p><p className="mt-1 text-xs text-slate-500">CPF, RG e dados pessoais.</p></button><button onClick={() => onEscolher("juridica")} className="rounded-xl border-2 border-slate-200 p-5 text-left hover:border-brand-500"><p className="font-semibold">Pessoa jurídica</p><p className="mt-1 text-xs text-slate-500">CNPJ, empresa e responsável.</p></button></div><button onClick={onCancelar} className="mt-5 text-sm font-semibold text-slate-500">Cancelar</button></section>; }
