import type { ClienteForm as Form, Pessoa } from "@/lib/clientes";
import { cepFormat, docFormat, phoneFormat } from "@/lib/clientes";

export default function ClienteForm({ pessoa, form, set, error, loadingCep, onBuscarCep }: { pessoa: Pessoa; form: Form; set: (key: string, value: string) => void; error?: string | null; loadingCep?: boolean; onBuscarCep: () => void }) {
  return <>
    {error && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <Card title="Dados pessoais / empresariais"><Grid><Input label={pessoa === "fisica" ? "Nome completo" : "Nome / Razão social"} k="nome" form={form} set={set} required/><Input label={pessoa === "fisica" ? "CPF" : "CNPJ"} k="documento" form={form} set={(_, value) => set("documento", docFormat(value, pessoa))} required/>{pessoa === "fisica" && <><Input label="RG" k="rg" form={form} set={set}/><Select label="Sexo" k="sexo" form={form} set={set} options={["Não informar", "Masculino", "Feminino"]}/><Input label="Data de nascimento" k="nascimento" form={form} set={set} type="date"/></>}<Input label="E-mail" k="email" form={form} set={set} type="email"/><Input label="Telefone" k="telefone" form={form} set={(_, value) => set("telefone", phoneFormat(value))} required placeholder="(45) 99999-9999"/><Area label="Observação" k="observacao" form={form} set={set}/></Grid></Card>
    {pessoa === "juridica" && <Card title="Dados exclusivos para pessoa jurídica"><Grid><Input label="Nome do responsável" k="responsavel" form={form} set={set}/><Input label="CPF do responsável" k="cpfResponsavel" form={form} set={(_, value) => set("cpfResponsavel", docFormat(value, "fisica"))}/><Input label="E-mail do responsável" k="emailResponsavel" form={form} set={set}/><Input label="Telefone do responsável" k="telefoneResponsavel" form={form} set={(_, value) => set("telefoneResponsavel", phoneFormat(value))}/><Input label="Inscrição estadual" k="inscricaoEstadual" form={form} set={set}/><Input label="Inscrição municipal" k="inscricaoMunicipal" form={form} set={set}/><Input label="Inscrição na SUFRAMA" k="suframa" form={form} set={set}/></Grid></Card>}
    <Card title="Dados de endereço"><Grid><Input label="CEP" k="cep" form={form} set={(_, value) => set("cep", cepFormat(value))} onBlur={onBuscarCep} required placeholder="00000-000"/><div className="flex items-end"><button type="button" onClick={onBuscarCep} disabled={loadingCep} className="w-full rounded-lg border border-brand-200 bg-brand-50 py-2.5 text-sm font-semibold text-brand-700">{loadingCep ? "Buscando..." : "Buscar endereço pelo CEP"}</button></div><Input label="Endereço" k="endereco" form={form} set={set} required/><Input label="Número" k="numero" form={form} set={set} required/><Input label="Complemento" k="complemento" form={form} set={set}/><Input label="Bairro" k="bairro" form={form} set={set} required/><Input label="UF" k="uf" form={form} set={set} required/><Input label="Município" k="municipio" form={form} set={set} required/><Input label="Código do município" k="codigoMunicipio" form={form} set={set}/></Grid></Card>
  </>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="border-b border-slate-100 pb-4 text-xs font-bold uppercase tracking-wider text-slate-700">{title}</h2><div className="mt-5">{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; }
function Input({ label, k, form, set, required, placeholder, type = "text", onBlur }: { label: string; k: string; form: Form; set: (key: string, value: string) => void; required?: boolean; placeholder?: string; type?: string; onBlur?: () => void }) { return <label className="text-xs font-semibold text-slate-600">{label}{required && <span className="text-red-500"> *</span>}<input value={form[k]} type={type} onChange={e => set(k, e.target.value)} onBlur={onBlur} required={required} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-brand-500"/></label>; }
function Select({ label, k, form, set, options }: { label: string; k: string; form: Form; set: (key: string, value: string) => void; options: string[] }) { return <label className="text-xs font-semibold text-slate-600">{label}<select value={form[k]} onChange={e => set(k, e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
function Area({ label, k, form, set }: { label: string; k: string; form: Form; set: (key: string, value: string) => void }) { return <label className="text-xs font-semibold text-slate-600 sm:col-span-2">{label}<textarea value={form[k]} onChange={e => set(k, e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"/></label>; }
